# Generated by Django 4.2.5 on 2023-12-02 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('audio_file', models.FileField(null=True, upload_to='audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('call_type', models.CharField(max_length=100)),
                ('call_duration', models.CharField(max_length=100)),
                ('call_date', models.CharField(max_length=100)),
                ('call_time', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TextComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('complaint', models.CharField(max_length=100)),
                ('complaint_time', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(default='Butwal', max_length=100)),
                ('province', models.CharField(default=7, max_length=100)),
                ('district', models.CharField(default='Rupandehi', max_length=100)),
                ('municipality', models.CharField(default='Suddhodhan', max_length=100)),
                ('wardno', models.CharField(default=4, max_length=100)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('criticality', models.CharField(default='low', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StatusTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('problem', models.CharField(max_length=100)),
                ('miistry', models.CharField(max_length=100)),
                ('complain_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.textcomplaint')),
            ],
        ),
    ]
