# Generated by Django 4.2.3 on 2023-07-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('call_type', models.CharField(max_length=100)),
                ('call_duration', models.CharField(max_length=100)),
                ('call_date', models.CharField(max_length=100)),
                ('call_time', models.CharField(max_length=100)),
            ],
        ),
    ]
