# Generated by Django 4.2.3 on 2023-08-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textcomplaint',
            name='criticality',
            field=models.CharField(default='low', max_length=100),
        ),
        migrations.AddField(
            model_name='textcomplaint',
            name='district',
            field=models.CharField(default='Rupandehi', max_length=100),
        ),
        migrations.AddField(
            model_name='textcomplaint',
            name='location',
            field=models.CharField(default='Butwal', max_length=100),
        ),
        migrations.AddField(
            model_name='textcomplaint',
            name='municipality',
            field=models.CharField(default='Suddhodhan', max_length=100),
        ),
        migrations.AddField(
            model_name='textcomplaint',
            name='province',
            field=models.CharField(default=7, max_length=100),
        ),
        migrations.AddField(
            model_name='textcomplaint',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
        migrations.AddField(
            model_name='textcomplaint',
            name='wardno',
            field=models.CharField(default=4, max_length=100),
        ),
        migrations.AlterField(
            model_name='textcomplaint',
            name='complain_id',
            field=models.AutoField(default=99, primary_key=True, serialize=False),
        ),
    ]
