# Generated by Django 4.2.3 on 2023-07-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('complaint', models.CharField(max_length=100)),
                ('complaint_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
