# Generated by Django 4.2.3 on 2023-08-11 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textcomplaint',
            name='complain_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
