# Generated by Django 4.2.5 on 2023-12-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='tag',
            new_name='category_tag',
        ),
        migrations.AddField(
            model_name='audiorecording',
            name='converted_text',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='textcomplaint',
            name='complain_tag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='textcomplaint',
            name='predicted_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='textcomplaint',
            name='district',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='textcomplaint',
            name='location',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='textcomplaint',
            name='municipality',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='textcomplaint',
            name='wardno',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
