# Generated by Django 4.2.5 on 2023-12-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_tag_category_category_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiorecording',
            name='converted_text',
            field=models.CharField(default='None', max_length=100, null=True),
        ),
    ]
