# Generated by Django 4.2.7 on 2023-12-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_audiorecording_converted_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiorecording',
            name='user',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
