# Generated by Django 4.2.7 on 2024-03-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_incrementaldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='incrementaldata',
            name='category',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='incrementaldata',
            name='complain',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
